{{- if .Values.beacon.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eth2-validator.beacon.serviceAccountName" . }}
  labels:
{{ include "eth2-validator.labels" . | nindent 4 }}
{{- end -}}
